// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1) {
  return window['go']['main']['App']['CreateEvent'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GoogleAuthURL(arg1) {
  return window['go']['main']['App']['GoogleAuthURL'](arg1);
}

export function GoogleExchangeCode(arg1) {
  return window['go']['main']['App']['GoogleExchangeCode'](arg1);
}

export function GoogleListHolidays(arg1) {
  return window['go']['main']['App']['GoogleListHolidays'](arg1);
}

export function GoogleLogout() {
  return window['go']['main']['App']['GoogleLogout']();
}

export function GooglePush() {
  return window['go']['main']['App']['GooglePush']();
}

export function GoogleRefreshTokens() {
  return window['go']['main']['App']['GoogleRefreshTokens']();
}

export function GoogleSync() {
  return window['go']['main']['App']['GoogleSync']();
}

export function GoogleTokenInfo() {
  return window['go']['main']['App']['GoogleTokenInfo']();
}

export function ListEvents() {
  return window['go']['main']['App']['ListEvents']();
}

export function SearchEvents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchEvents'](arg1, arg2, arg3, arg4);
}

export function UpdateEvent(arg1) {
  return window['go']['main']['App']['UpdateEvent'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
